print('Hello. What is your name?')
user_name = input()
print('It\'s nice to meet you,', user_name, '. How old are you?')
user_age = input()
print('I see that you are still quite young at only', user_age, '.')
print('Where do you live?')
user_address = input()
print('Wow! I\'ve always wanted to go to', user_address, '. Thanks for chatting with me. Bye!')
exit()
